### ISSUE TITLE
复制按钮只能复制最后一行

### ISSUE THREAD

**Issue by shanglanxin** [Ukenn2112/MOJiBobPlugin#1]
![image](https://github.com/Ukenn2112/MOJiBobPlugin/assets/6736427/46f09041-d6f8-41a4-89f0-eec9c460af1b)
点击复制按钮，只能复制最后一行【[名] 末尾最后(物事の終わり。すえ。)】

逻辑上应该复制全部内容？
或者有办法复制全部内容吗？

**Comment by Ukenn2112** [comment]
这个是Bob的设计问题，Bob设计复制的那个按钮是复制所传给`toParagraphs`的内容，而所传回字典键`toDict`不是同一个，如果两个键都传相同的内容后面会导致重复显示一遍相同的内容，所以无法实现这个功能。

**Comment by shanglanxin** [comment]
原来如此，谢谢。
想要粘贴到Anki里面进行记忆。
