### ISSUE TITLE
出现未定义错误

### ISSUE THREAD

**Issue by mkblbj** [Ukenn2112/MOJiBobPlugin#5]
麻烦问下作者，今天提示更新1.0.2后出现如下错误，无法查词。

> 出现错误: undefined is not an object (evaluating 'searchResponse.data.result.results["search-all"]')
请尝试重新查询或联系我们。 
https://github.com/Ukenn2112/MOJiBobPlugin/issues/new

![CleanShot 2024-12-14 at 11  49 10@2x](https://github.com/user-attachments/assets/343f9b2a-d358-4111-8402-a49b203aa293)

**Comment by Ukenn2112** [comment]
谢谢反馈
可能MOJI的API又变了，稍晚我看一下

Ps：其实1.0.2版本在2个月前就发布了（

**Comment by Ukenn2112** [comment]
已在最新版本修复
https://github.com/Ukenn2112/MOJiBobPlugin/releases/tag/v1.0.3

**Comment by mkblbj** [comment]
感谢，火箭速度！

**Comment by Verdurea** [comment]
感谢，更新修复好快，一直在用，真的给力！
